name: Add Issue to Central Project

on:
  issues:
    types: [opened]

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add To GitHub Projects
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/GEC-SKP-DEV/projects/6
          github-token: ${{ secrets.CENTRAL_PROJECT_PAT }}
          # optional: only add issues labeled "bug"
          labeled: bug
          label-operator: OR
